import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { YandexMetricaProvider } from "next-yandex-metrica";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <YandexMetricaProvider
          tagID={105188278}
          initParameters={{
            webvisor: true,
            trackHash: true,
            clickmap: true,
            ecommerce: "dataLayer",
            accurateTrackBounce: true,
            trackLinks: true,
          }}
          router="app"
        >
          {children}
        </YandexMetricaProvider>
      </body>
    </html>
  );
}
